---
- name: Configure Git user name
  git_config:
    name: user.name
    value: "{{ git_user_name }}"
    scope: global

- name: Configure Git user email
  git_config:
    name: user.email
    value: "{{ git_user_email }}"
    scope: global

- name: Configure Git core editor
  git_config:
    name: core.editor
    value: vim
    scope: global

- name: Generate SSH key if not present
  openssh_keypair:
    path: "/home/{{ user_name }}/.ssh/id_rsa"
    type: rsa
    size: 4096
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0600'
    comment: "{{ git_user_email }}"
    force: no
  register: ssh_keypair
  when: not ssh_keypair_stat.stat.exists
  vars:
    ssh_keypair_stat:
      stat: path="/home/{{ user_name }}/.ssh/id_rsa.pub"

- name: Start ssh-agent and add key
  shell: |
    eval "$(ssh-agent -s)"
    ssh-add /home/{{ user_name }}/.ssh/id_rsa
  args:
    executable: /bin/bash
  become: false

- name: Display public SSH key
  debug:
    msg: "Your public SSH key:\n{{ lookup('file', '/home/' + user_name + '/.ssh/id_rsa.pub') }}"
  become: false