---
- name: Update and upgrade apt packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist

- name: Remove LibreOffice Core
  ansible.builtin.apt:
    name: libreoffice-core
    state: absent
    purge: true

- name: Clean apt cache and remove unnecessary packages
  ansible.builtin.apt:
    autoclean: true
    autoremove: true

- name: Install essential apt packages
  ansible.builtin.apt:
    name: "{{ packages_apt }}"
    state: present

- name: Add Flathub repository
  ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  args:
    creates: /var/lib/flatpak/repo/flathub.trustedkeys.gpg

- name: Install OBS Studio via Flatpak
  flatpak:
    name: com.obsproject.Studio
    state: present
    remote: flathub

- name: Install Neovim via Snap
  snap:
    name: nvim
    classic: true
    state: present

- name: Install pipx
  ansible.builtin.pip:
    name: pipx
    executable: pip3
    extra_args: --user
  become: false

- name: Ensure ~/.local/bin is in PATH
  ansible.builtin.lineinfile:
    path: "/home/{{ user_name }}/.zshrc"
    line: 'update_path "$HOME/.local/bin"'
    state: present
  become: false
