---
- name: PopOS Setup Playbook
  hosts: localhost
  become: true
  vars_files:
    - vars/main.yml

  roles:
    - common

    - role: git
      tags: git

    - role: zsh
      tags: zsh

    - role: sdkman
      tags: sdkman

    - role: fonts
      tags: fonts

    - role: development_dirs
      tags: development_dirs

    - role: rust
      tags: rust

    - role: librewolf
      tags: librewolf
