---
- name: PopOS Setup Playbook
  hosts: localhost
  become: true
  vars_files:
    - vars/main.yml

  roles:
    - common
    - git
    - zsh
    - sdkman
    - rust
    - fonts
    - dotfiles
    - development_dirs