#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

[[layers]]
  name = "colorscheme"
  random_theme = true
  frequency = "weekly"

[[custom_plugins]]
  repo = "tribela/vim-transparent"
  merged = 0

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "smart"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "lang#python"
  format_on_save=true

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#docker"

[[layers]]
  name = "git"

[[layers]]
  name = "lang#html"
  format_on_save=true

[[layers]]
  name = "lang#javascript"
  format_on_save=true

[[layers]]
  name = "lang#typescript"
  format_on_save=true

#[[layers]]
#  name = "lang#java"


#[[layers]]
#  name = "lang#scala"

