---
- name: Clone InstallOS repository
  git:
    repo: "{{ installos_repo }}"
    dest: "/home/{{ user_name }}/InstallOS"
    version: master
    accept_hostkey: yes
  become: false

- name: Remove existing .bashrc and .zshrc
  file:
    path: "/home/{{ user_name }}/.{{ item }}"
    state: absent
  loop:
    - bashrc
    - zshrc
  become: false

- name: Symlink .bashrc and .zshrc from InstallOS
  file:
    src: "/home/{{ user_name }}/InstallOS/.{{ item }}"
    dest: "/home/{{ user_name }}/.{{ item }}"
    state: link
    force: yes
  loop:
    - bashrc
    - zshrc
  become: false

- name: Create .SpaceVim.d directory
  file:
    path: "/home/{{ user_name }}/.SpaceVim.d"
    state: directory
  become: false

- name: Symlink init.toml from InstallOS
  file:
    src: "/home/{{ user_name }}/InstallOS/.SpaceVim.d/init.toml"
    dest: "/home/{{ user_name }}/.SpaceVim.d/init.toml"
    state: link
    force: yes
  become: false

- name: Install SpaceVim
  shell: curl -sLf https://spacevim.org/install.sh | bash
  args:
    executable: /bin/bash
  become: false
