---
- name: Install Rust via rustup
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    executable: /bin/bash
  environment:
    CARGO_HOME: "/home/{{ user_name }}/.cargo"
  become: false

- name: Ensure .cargo/bin is in PATH
  lineinfile:
    path: "/home/{{ user_name }}/.zshrc"
    line: 'update_path "$HOME/.cargo/bin"' 
    state: present
  become: false

- name: Install cargo-binstall
  shell: |
    curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
  args:
    executable: /bin/bash
  become: false

- name: Install Zellij via cargo-binstall
  shell: "~/.cargo/bin/cargo-binstall zellij -y"
  args:
    executable: /bin/bash
  become: false