---
- name: Create development directories
  ansible.builtin.file:
    path: "/home/{{ user_name }}/Development/{{ item }}"
    state: directory
    mode: "0775"
    owner: "{{ user_name }}"
  loop: "{{ development_directories }}"
  become: false
